/* 
* SPDX-License-Identifier: LicenseRef-AllRightsReserved
*
* License-Url: https://github.com/0xkrauser/erc721m-indexer/LICENSES/LicenseRef-AllRightsReserved.txt
*
* SPDX-FileType: SOURCE
*
* SPDX-FileCopyrightText: 2024 Johannes Krauser III <krauser@co.xyz>
*
* SPDX-FileContributor: Johannes Krauser III <krauser@co.xyz>

* This file is generated by generateSchemaTypes.ts. Do not modify it manually.
*/

/* eslint-disable typescript-sort-keys/interface */
type Contract = {
  id: string
  chainId: number
  address: string
  wallet_id: string
  collection_id: string | undefined
  creator_id: string | undefined
  owner_id: string | undefined
  paused: boolean | undefined
  createdBlockNumber: number | undefined
  createdTimestamp: number | undefined
  encounteredBlockNumber: number | undefined
  encounteredTimestamp: number | undefined
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_CONTRACT: Contract = {
  id: "",
  chainId: 0,
  address: "",
  wallet_id: "",
  collection_id: undefined,
  creator_id: undefined,
  owner_id: undefined,
  paused: undefined,
  createdBlockNumber: undefined,
  createdTimestamp: undefined,
  encounteredBlockNumber: undefined,
  encounteredTimestamp: undefined,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Contract

type Collection = {
  id: string
  name: string | undefined
  symbol: string | undefined
  contract_id: string
  totalSupply: bigint
  maxSupply: bigint | undefined
  erc2981_id: string | undefined
  allocationPc: bigint[]
  referralFeePc: bigint
  reservedSupply: bigint
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_COLLECTION: Collection = {
  id: "",
  name: undefined,
  symbol: undefined,
  contract_id: "",
  totalSupply: 0n,
  maxSupply: undefined,
  erc2981_id: undefined,
  allocationPc: [],
  referralFeePc: 0n,
  reservedSupply: 0n,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Collection

type ERC2981Info = {
  id: string
  royaltyPc: bigint | undefined
  royaltyReceiver_id: string
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_ERC2981INFO: ERC2981Info = {
  id: "",
  royaltyPc: undefined,
  royaltyReceiver_id: "",
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies ERC2981Info

type Token = {
  id: string
  tokenId: bigint
  collection_id: string
  ownerAddress: string | undefined
  minterAddress: string | undefined
  minter_id: string | undefined
  owner_id: string | undefined
  erc2981_id: string | undefined
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_TOKEN: Token = {
  id: "",
  tokenId: 0n,
  collection_id: "",
  ownerAddress: undefined,
  minterAddress: undefined,
  minter_id: undefined,
  owner_id: undefined,
  erc2981_id: undefined,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Token

type TokenAmount = {
  id: string
  token_id: string
  wallet_id: string
  amount: bigint
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_TOKEN_AMOUNT: TokenAmount = {
  id: "",
  token_id: "",
  wallet_id: "",
  amount: 0n,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies TokenAmount

type List = {
  id: string
  listId: bigint
  collection_id: string
  merkleRoot: string
  totalSupply: bigint
  maxSupply: bigint
  userSupply: bigint
  unit: bigint
  price: bigint
  start: bigint
  end: bigint
  reserved: boolean
  paused: boolean
  deleted: boolean
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_LIST: List = {
  id: "",
  listId: 0n,
  collection_id: "",
  merkleRoot: "",
  totalSupply: 0n,
  maxSupply: 0n,
  userSupply: 0n,
  unit: 0n,
  price: 0n,
  start: 0n,
  end: 0n,
  reserved: false,
  paused: false,
  deleted: false,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies List

type ListClaimed = {
  id: string
  wallet_id: string
  list_id: string
  amount: bigint
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_LIST_CLAIMED: ListClaimed = {
  id: "",
  wallet_id: "",
  list_id: "",
  amount: 0n,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies ListClaimed

type ReferralLog = {
  id: string
  transactionHash: string
  logIndex: number
  referral_id: string
  referred_id: string
  amount: bigint
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_REFERRAL_LOG: ReferralLog = {
  id: "",
  transactionHash: "",
  logIndex: 0,
  referral_id: "",
  referred_id: "",
  amount: 0n,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies ReferralLog

type RoyaltiesUpdateLog = {
  id: string
  chainid: number
  transactionHash: string
  logIndex: number
  collection_id: string | undefined
  token_id: string | undefined
  sender_id: string
  tokenId: bigint
  royaltyPc: bigint | undefined
  royaltyReceiver_id: string
  blockNumber: number
  blockTimestamp: number
}

export const INITIAL_ROYALTIES_UPDATE_LOG: RoyaltiesUpdateLog = {
  id: "",
  chainid: 0,
  transactionHash: "",
  logIndex: 0,
  collection_id: undefined,
  token_id: undefined,
  sender_id: "",
  tokenId: 0n,
  royaltyPc: undefined,
  royaltyReceiver_id: "",
  blockNumber: 0,
  blockTimestamp: 0,
} satisfies RoyaltiesUpdateLog

type Wallet = {
  id: string
  contract_id: string | undefined
  collectionsCreatedCount: number
  collectionsOwnedCount: number
  treasuriesCreatedCount: number
  tokensOwnedCount: number
  tokensMintedCount: number
  itemsSold: bigint
  itemsBought: bigint
  encounteredTimestamp: number
  updatedTimestamp: number
}

export const INITIAL_WALLET: Wallet = {
  id: "",
  contract_id: undefined,
  collectionsCreatedCount: 0,
  collectionsOwnedCount: 0,
  treasuriesCreatedCount: 0,
  tokensOwnedCount: 0,
  tokensMintedCount: 0,
  itemsSold: 0n,
  itemsBought: 0n,
  encounteredTimestamp: 0,
  updatedTimestamp: 0,
} satisfies Wallet

type CollectionActivity = {
  id: string
  collection_id: string
  wallet_id: string
  spent: bigint
  mintCount: bigint
  referralFeesEarned: bigint
  referralCount: bigint
  referredCount: bigint
  referralAmount: bigint
  referredAmount: bigint
  bought: bigint
  sold: bigint
  createdTimestamp: number
  createdBlockNumber: number
  updatedTimestamp: number
  updatedBlockNumber: number
}

export const INITIAL_COLLECTION_ACTIVITY: CollectionActivity = {
  id: "",
  collection_id: "",
  wallet_id: "",
  spent: 0n,
  mintCount: 0n,
  referralFeesEarned: 0n,
  referralCount: 0n,
  referredCount: 0n,
  referralAmount: 0n,
  referredAmount: 0n,
  bought: 0n,
  sold: 0n,
  createdTimestamp: 0,
  createdBlockNumber: 0,
  updatedTimestamp: 0,
  updatedBlockNumber: 0,
} satisfies CollectionActivity
