/* 
* SPDX-License-Identifier: LicenseRef-AllRightsReserved
*
* License-Url: https://github.com/0xkrauser/erc721m-indexer/LICENSES/LicenseRef-AllRightsReserved.txt
*
* SPDX-FileType: SOURCE
*
* SPDX-FileCopyrightText: 2024 Johannes Krauser III <krauser@co.xyz>
*
* SPDX-FileContributor: Johannes Krauser III <krauser@co.xyz>

* This file is generated by generateSchemaTypes.ts. Do not modify it manually.
*/

/* eslint-disable typescript-sort-keys/interface */
type Contract = {
  id: string
  chainId: number
  address: string
  wallet_id: string
  collection_id: string | undefined
  creator_id: string | undefined
  owner_id: string | undefined
  paused: boolean | undefined
  createdBlockNumber: number | undefined
  createdTimestamp: number | undefined
  encounteredBlockNumber: number | undefined
  encounteredTimestamp: number | undefined
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_CONTRACT: Contract = {
  id: "",
  chainId: 0,
  address: "",
  wallet_id: "",
  collection_id: undefined,
  creator_id: undefined,
  owner_id: undefined,
  paused: undefined,
  createdBlockNumber: undefined,
  createdTimestamp: undefined,
  encounteredBlockNumber: undefined,
  encounteredTimestamp: undefined,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Contract

type Collection = {
  id: string
  name: string | undefined
  symbol: string | undefined
  contract_id: string
  totalSupply: bigint
  maxSupply: bigint | undefined
  erc2981_id: string | undefined
  launchpad_id: string | undefined
  nftPolicy_id: string | undefined
  feeRecipients: string[]
  fees: bigint[]
  allocationPc: bigint[]
  referralFeePc: bigint
  treasury_id: string | undefined
  splitter_id: string | undefined
  reservedSupply: bigint
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_COLLECTION: Collection = {
  id: "",
  name: undefined,
  symbol: undefined,
  contract_id: "",
  totalSupply: 0n,
  maxSupply: undefined,
  erc2981_id: undefined,
  launchpad_id: undefined,
  nftPolicy_id: undefined,
  feeRecipients: [],
  fees: [],
  allocationPc: [],
  referralFeePc: 0n,
  treasury_id: undefined,
  splitter_id: undefined,
  reservedSupply: 0n,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Collection

type ERC2981Info = {
  id: string
  royaltyPc: bigint | undefined
  royaltyReceiver_id: string
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_ERC2981INFO: ERC2981Info = {
  id: "",
  royaltyPc: undefined,
  royaltyReceiver_id: "",
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies ERC2981Info

type Token = {
  id: string
  tokenId: bigint
  collection_id: string
  ownerAddress: string | undefined
  minterAddress: string | undefined
  minter_id: string | undefined
  owner_id: string | undefined
  erc2981_id: string | undefined
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_TOKEN: Token = {
  id: "",
  tokenId: 0n,
  collection_id: "",
  ownerAddress: undefined,
  minterAddress: undefined,
  minter_id: undefined,
  owner_id: undefined,
  erc2981_id: undefined,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Token

type TokenAmount = {
  id: string
  token_id: string
  wallet_id: string
  amount: bigint
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_TOKEN_AMOUNT: TokenAmount = {
  id: "",
  token_id: "",
  wallet_id: "",
  amount: 0n,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies TokenAmount

type List = {
  id: string
  listId: bigint
  collection_id: string
  merkleRoot: string
  totalSupply: bigint
  maxSupply: bigint
  userSupply: bigint
  unit: bigint
  price: bigint
  start: bigint
  end: bigint
  reserved: boolean
  paused: boolean
  deleted: boolean
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_LIST: List = {
  id: "",
  listId: 0n,
  collection_id: "",
  merkleRoot: "",
  totalSupply: 0n,
  maxSupply: 0n,
  userSupply: 0n,
  unit: 0n,
  price: 0n,
  start: 0n,
  end: 0n,
  reserved: false,
  paused: false,
  deleted: false,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies List

type ListClaimed = {
  id: string
  wallet_id: string
  list_id: string
  amount: bigint
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_LIST_CLAIMED: ListClaimed = {
  id: "",
  wallet_id: "",
  list_id: "",
  amount: 0n,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies ListClaimed

type ReferralLog = {
  id: string
  transactionHash: string
  logIndex: number
  referral_id: string
  referred_id: string
  amount: bigint
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_REFERRAL_LOG: ReferralLog = {
  id: "",
  transactionHash: "",
  logIndex: 0,
  referral_id: "",
  referred_id: "",
  amount: 0n,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies ReferralLog

type Launchpad = {
  id: string
  contract_id: string
  collectionsCreatedCount: number
  treasuriesCreatedCount: number
  splittersCreatedCount: number
  approvedCreators: string[]
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_LAUNCHPAD: Launchpad = {
  id: "",
  contract_id: "",
  collectionsCreatedCount: 0,
  treasuriesCreatedCount: 0,
  splittersCreatedCount: 0,
  approvedCreators: [],
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Launchpad

type Treasury = {
  id: string
  contract_id: string
  launchpad_id: string
  treasuryPolicy_id: string
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_TREASURY: Treasury = {
  id: "",
  contract_id: "",
  launchpad_id: "",
  treasuryPolicy_id: "",
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Treasury

type Splitter = {
  id: string
  contract_id: string
  launchpad_id: string
  splitterPolicy_id: string
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_SPLITTER: Splitter = {
  id: "",
  contract_id: "",
  launchpad_id: "",
  splitterPolicy_id: "",
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Splitter

type NftPolicy = {
  id: string
  policyId: bigint
  launchpad_id: string
  masterCopy: string
  merkleRoot: string
  feeRecipients: string[]
  feeRanges: bigint[][]
  royaltyRange: bigint[]
  paused: boolean
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_NFT_POLICY: NftPolicy = {
  id: "",
  policyId: 0n,
  launchpad_id: "",
  masterCopy: "",
  merkleRoot: "",
  feeRecipients: [],
  feeRanges: [],
  royaltyRange: [],
  paused: false,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies NftPolicy

type TreasuryPolicy = {
  id: string
  policyId: bigint
  launchpad_id: string
  masterCopy: string
  merkleRoot: string
  feeRecipients: string[]
  feeRanges: bigint[][]
  royaltyRange: bigint[]
  interestRateRange: bigint[]
  termLimitRange: bigint[]
  paused: boolean
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_TREASURY_POLICY: TreasuryPolicy = {
  id: "",
  policyId: 0n,
  launchpad_id: "",
  masterCopy: "",
  merkleRoot: "",
  feeRecipients: [],
  feeRanges: [],
  royaltyRange: [],
  interestRateRange: [],
  termLimitRange: [],
  paused: false,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies TreasuryPolicy

type SplitterPolicy = {
  id: string
  policyId: bigint
  launchpad_id: string
  masterCopy: string
  merkleRoot: string
  feeRecipients: string[]
  feeRanges: bigint[][]
  paused: boolean
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_SPLITTER_POLICY: SplitterPolicy = {
  id: "",
  policyId: 0n,
  launchpad_id: "",
  masterCopy: "",
  merkleRoot: "",
  feeRecipients: [],
  feeRanges: [],
  paused: false,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies SplitterPolicy

type ApprovedCreatorUpdateLog = {
  id: string
  transactionHash: string
  from_id: string
  launchpad_id: string
  user_id: string
  state: boolean
  blockNumber: number
  blockTimestamp: number
}

export const INITIAL_APPROVED_CREATOR_UPDATE_LOG: ApprovedCreatorUpdateLog = {
  id: "",
  transactionHash: "",
  from_id: "",
  launchpad_id: "",
  user_id: "",
  state: false,
  blockNumber: 0,
  blockTimestamp: 0,
} satisfies ApprovedCreatorUpdateLog

type RoyaltiesUpdateLog = {
  id: string
  chainid: number
  transactionHash: string
  logIndex: number
  collection_id: string | undefined
  token_id: string | undefined
  sender_id: string
  tokenId: bigint
  royaltyPc: bigint | undefined
  royaltyReceiver_id: string
  blockNumber: number
  blockTimestamp: number
}

export const INITIAL_ROYALTIES_UPDATE_LOG: RoyaltiesUpdateLog = {
  id: "",
  chainid: 0,
  transactionHash: "",
  logIndex: 0,
  collection_id: undefined,
  token_id: undefined,
  sender_id: "",
  tokenId: 0n,
  royaltyPc: undefined,
  royaltyReceiver_id: "",
  blockNumber: 0,
  blockTimestamp: 0,
} satisfies RoyaltiesUpdateLog

type OrderFulfilledLog = {
  id: string
  transactionHash: string
  chainId: number
  logIndex: number
  sender_id: string
  orderHash: string
  offerer_id: string
  recipient_id: string
  zone: string
  platform: string
  blockNumber: number
  blockTimestamp: number
}

export const INITIAL_ORDER_FULFILLED_LOG: OrderFulfilledLog = {
  id: "",
  transactionHash: "",
  chainId: 0,
  logIndex: 0,
  sender_id: "",
  orderHash: "",
  offerer_id: "",
  recipient_id: "",
  zone: "",
  platform: "",
  blockNumber: 0,
  blockTimestamp: 0,
} satisfies OrderFulfilledLog

type SpentItem = {
  id: string
  order_id: string
  itemType_id: string | undefined
  token: string
  identifier: bigint
  amount: bigint
}

export const INITIAL_SPENT_ITEM: SpentItem = {
  id: "",
  order_id: "",
  itemType_id: undefined,
  token: "",
  identifier: 0n,
  amount: 0n,
} satisfies SpentItem

type ReceivedItem = {
  id: string
  order_id: string
  itemType_id: string | undefined
  token: string
  identifier: bigint
  amount: bigint
  recipient: string
}

export const INITIAL_RECEIVED_ITEM: ReceivedItem = {
  id: "",
  order_id: "",
  itemType_id: undefined,
  token: "",
  identifier: 0n,
  amount: 0n,
  recipient: "",
} satisfies ReceivedItem

type Counter = {
  id: string
  chainId: number
  seaport: string
  wallet_id: string
  counter: bigint
  createdBlockNumber: number
  createdTimestamp: number
  updatedBlockNumber: number
  updatedTimestamp: number
}

export const INITIAL_COUNTER: Counter = {
  id: "",
  chainId: 0,
  seaport: "",
  wallet_id: "",
  counter: 0n,
  createdBlockNumber: 0,
  createdTimestamp: 0,
  updatedBlockNumber: 0,
  updatedTimestamp: 0,
} satisfies Counter

type NftSales = {
  id: string
  chainId: number
  transactionHash: string
  logIndex: number
  orderHash: string
  contract_id: string
  token_id: string
  saleAmount: bigint
  saleToken: string
  offerer_id: string
  recipient_id: string
  createdBlockNumber: number
  createdTimestamp: number
}

export const INITIAL_NFT_SALES: NftSales = {
  id: "",
  chainId: 0,
  transactionHash: "",
  logIndex: 0,
  orderHash: "",
  contract_id: "",
  token_id: "",
  saleAmount: 0n,
  saleToken: "",
  offerer_id: "",
  recipient_id: "",
  createdBlockNumber: 0,
  createdTimestamp: 0,
} satisfies NftSales

type Wallet = {
  id: string
  contract_id: string | undefined
  collectionsCreatedCount: number
  collectionsOwnedCount: number
  treasuriesCreatedCount: number
  tokensOwnedCount: number
  tokensMintedCount: number
  itemsSold: bigint
  itemsBought: bigint
  encounteredTimestamp: number
  updatedTimestamp: number
}

export const INITIAL_WALLET: Wallet = {
  id: "",
  contract_id: undefined,
  collectionsCreatedCount: 0,
  collectionsOwnedCount: 0,
  treasuriesCreatedCount: 0,
  tokensOwnedCount: 0,
  tokensMintedCount: 0,
  itemsSold: 0n,
  itemsBought: 0n,
  encounteredTimestamp: 0,
  updatedTimestamp: 0,
} satisfies Wallet

type CollectionActivity = {
  id: string
  collection_id: string
  wallet_id: string
  spent: bigint
  mintCount: bigint
  referralFeesEarned: bigint
  referralCount: bigint
  referredCount: bigint
  referralAmount: bigint
  referredAmount: bigint
  bought: bigint
  sold: bigint
  createdTimestamp: number
  createdBlockNumber: number
  updatedTimestamp: number
  updatedBlockNumber: number
}

export const INITIAL_COLLECTION_ACTIVITY: CollectionActivity = {
  id: "",
  collection_id: "",
  wallet_id: "",
  spent: 0n,
  mintCount: 0n,
  referralFeesEarned: 0n,
  referralCount: 0n,
  referredCount: 0n,
  referralAmount: 0n,
  referredAmount: 0n,
  bought: 0n,
  sold: 0n,
  createdTimestamp: 0,
  createdBlockNumber: 0,
  updatedTimestamp: 0,
  updatedBlockNumber: 0,
} satisfies CollectionActivity
