export const LICENSE_BLOCK = `# SPDX-License-Identifier: LicenseRef-AllRightsReserved
#
# License-Url: https://github.com/0xkrauser/erc721m-indexer/LICENSES/LicenseRef-AllRightsReserved.txt
#
# SPDX-FileType: SOURCE
#
# SPDX-FileCopyrightText: 2024 Johannes Krauser III <krauser@co.xyz>
#
# SPDX-FileContributor: Johannes Krauser III <krauser@co.xyz>

# This file is generated by generateSchema.ts. Do not modify it manually.\n
`

export const JAVASCRIPT_LICENSE_BLOCK = `/* 
* SPDX-License-Identifier: LicenseRef-AllRightsReserved
*
* License-Url: https://github.com/0xkrauser/erc721m-indexer/LICENSES/LicenseRef-AllRightsReserved.txt
*
* SPDX-FileType: SOURCE
*
* SPDX-FileCopyrightText: 2024 Johannes Krauser III <krauser@co.xyz>
*
* SPDX-FileContributor: Johannes Krauser III <krauser@co.xyz>

* This file is generated by generateSchemaTypes.ts. Do not modify it manually.
*/\n
`
